product_name = input("Тауардың атын енгізіңіз: ") 
price = input("Тауардың бағасын енгізіңіз(тг): ")
quantity = input("Қанша дана (штук) аласыз: ")
total_price = int(price) * int(quantity)
print("\n========== СУПЕРМАРКЕТ ЧЕГІ ========== ")
print(f"Тауар аты: {product_name}")
print(f"Бағасы: {price} тг")
print(f"Саны: {quantity} шт")
print(f"Жалпы құны: {total_price} тг")
print("================================")